// Generated by Makefile / scripts/build-app.sh — do not edit by hand.
// At dev time this file ships the .version literal; release builds overwrite it.
import Foundation

enum BuildInfo {
    static let version: String = "0.1.0"
    static let bundleIdentifier: String = "com.fullstackoptimization.bgbgone-app"
    static let osLogSubsystem: String = "com.arthur-ficial.bgbgone-app"
}
